Caste = ['All equal', 'Strong Lead', 'Born Into', 'Employment', 'Skill']
Religion = ['No one major religion', 'Monothieistic', 'Polythieistic', 'Atheistic']
Language = ['Abundance of language', 'One major language', 'A couple major languages']
Languages = ['FirtLang','SecLang','ThiLang','FifLang','SixLang','SevLeng','EigLang','NinLang','TenLeng']
Food = ['Focus on spices', 'Focus on herbs', 'Focus on sweetness', 'Focus on savory', 'Focus on unseasoned', 'Mixed food focus', 'All focuses']
Art = ['Focus on abstract', 'Focus on realism', 'Focus on realism', 'Focus on impressionism', 'No real focus', 'Sporatic focus']
Music = ['String focus', 'Woodwind focus', 'Percussion focus', 'Brass focus', 'Mixed focus', 'No focus', 'Wide focus']
Resource = ['Inland-water', 'Ocean', 'Farmland', 'Lumber', 'Quarry[stone]', 'Mine[ores/gems]', 'Finished Goods', 'Exotics']
Gender = ['Male','Female','Non-Binary']
GenderRolls = ['Equal', 'Patriarchal', 'Matriarchal']
Trade = ['Abundance', 'Some', 'Very little', 'None']
Events = ['Events through the year','A few major events','No major events']
Verted = ['Introverted','Extroverted'] 
# the idea is this will affect thier likyhood to like cities with more events
Authority = ['No major authority', 'Single ruler', 'Council', 'Single ruler with council', 'Elected single ruler', 'Elected council', 'Elected single ruler and council']
Authority0 = ['Elected','No major authority','Inherited']
# if Authority0 is 0 or 2 then also need to select from Authority1
Authority1 = ['Single ruler','Single ruler with inherited council','Single ruler with elected council','Council']